spring.application.name=tcc-server
spring.profiles.active=${ACTIVE_PROFILE:dev}
spring.datasource.url=${POSTGRESSQL_URL}
spring.datasource.username=${POSTGRESSQL_USER}
spring.datasource.password=${POSTGRESSQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

api.security.token.secret=${JWT_SECRET:my-secret-key}
api.security.token.issuer=${JWT_ISSUER:pagtesouro-api}
api.security.token.audience=${JWT_AUDIENCE:api}
api.security.token.expiration-time-in-minutes=${JWT_EXPIRATION_HOURS:2}
api.pagtesouro.base_url = ${PAGTESOURO_BASE_URL:"https://valpagtesouro.tesouro.gov.br"}
api.pagtesouro.token_salinas = ${PAGTESOURO_TOKEN_SALINAS}