spring.application.name=tcc-server
spring.profiles.active=${ACTIVE_PROFILE:dev}

# Configuração de Porta Dinâmica para Render / Railway / Heroku
server.port=${PORT:8080}

spring.datasource.url=${POSTGRESSQL_URL:${SPRING_DATASOURCE_URL:}}
spring.datasource.username=${POSTGRESSQL_USER:${SPRING_DATASOURCE_USERNAME:}}
spring.datasource.password=${POSTGRESSQL_PASSWORD:${SPRING_DATASOURCE_PASSWORD:}}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

api.security.token.secret=${JWT_SECRET:my-secret-key}
api.security.token.issuer=${JWT_ISSUER:pagtesouro-api}
api.security.token.audience=${JWT_AUDIENCE:api}
api.security.token.expiration-time-in-minutes=${JWT_EXPIRATION_HOURS:20}
api.security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
api.security.initial-admin-email=${INITIAL_ADMIN_EMAIL:}
api.pagtesouro.base_url = ${PAGTESOURO_BASE_URL:https://valpagtesouro.tesouro.gov.br}
api.pagtesouro.token_salinas = ${PAGTESOURO_TOKEN_SALINAS}
api.pagtesouro.url_notificacao = ${PAGTESOURO_URL_NOTIFICACAO:https://meudominio.edu.br/api/payments/webhook}

# Configuração do Cron para o Daemon de Conciliação Failsafe do PagTesouro (Padrão: A cada hora)
api.pagtesouro.daemon.cron=${PAGTESOURO_DAEMON_CRON:0 0 * * * *}